# Generated by Django 3.1.1 on 2020-09-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionformmodel',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
