# Generated by Django 3.1.1 on 2020-09-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_form', '0002_auto_20200921_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionformmodel',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
