# Generated by Django 3.1.1 on 2020-09-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_form', '0003_auto_20200921_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionformmodel',
            name='birthday',
            field=models.CharField(max_length=255),
        ),
    ]
